-- Adds a shareable preview link to every inquiry. The slug is generated by
-- the app (not the database) so it can draw on the project name/description,
-- but the column lives here so guests (no account) can be sent straight to
-- /preview/<slug> instead of needing to sign in to check on their site.

alter table inquiries
  add column if not exists slug text,
  add column if not exists preview_url text,
  add column if not exists preview_sent_at timestamptz;

create unique index if not exists inquiries_slug_key on inquiries (slug);

-- The preview page is a capability link: anyone holding the (long, random)
-- slug can view that one inquiry, signed in or not. It reads through the
-- service-role client (see lib/inquiries.ts), which already bypasses RLS,
-- so no new policy is required here — this comment just documents why.
